name: "Matthew Morey"
description: "Personal website of Matthew Morey, an engineer, developer, hacker, creator, tinkerer, surfer, snowboarder, and husband."
keywords:
- Matthew Morey
- Matt(hew) Morey
- iOS developer
- programming
- engineer
- surfer
- snowboarder
- hacker
- creator
baseurl: /
url: http://localhost:4000
production_url: "http://matthewmorey.com"
paginate: 5
markdown: redcarpet
redcarpet:
  extensions: []
permalink: /:title
pygments: true
exclude: [README.md, TODO.md, Gemfile*]
include: [.htaccess]
safe: true
